### ISSUE TITLE
need parenthesis to make iterable for tuple function

### ISSUE THREAD

**Issue by liruohan0714** [icecube/skyllh#194] opened 2023-10-23 16:47 UTC
https://github.com/icecube/skyllh/blob/134c1b09c56c07d5565a9c73b80e8b109e0f997d/skyllh/core/signal_generation.py#L55

**Comment by martwo** [comment] 2023-10-23 16:51
This issue is unclear to me what the problem is. Please describe the issue.

**Comment by martwo** [comment] 2023-10-23 16:57
Fixed via commit 13154d1

**Closed by martwo** 2023-10-23 16:57 UTC
